### ISSUE TITLE
Getting error, "find: I cannot figure out how to interpret ?[Today's Date]? as a date or time"

### ISSUE THREAD

**Issue by Dysfunkshnl** [atrac17/MiSTer_MAME_SCRIPTS#29]
Getting the error whenever the Mame Getter script is run to find new ROMS from loaded MRAs. Anyone else seeing this?

**Comment by Dysfunkshnl** [comment]
Changing ini from hbmame getter to update_all.ini seems to have resolved the issue.

**Comment by atrac17** [comment]
Issue reported resolved by users.
