### ISSUE TITLE
CURL timeouts, incomplete zips which are not removed

### ISSUE THREAD

**Issue by movisman** [atrac17/MiSTer_MAME_SCRIPTS#33]
Hi there,

Hope you are good. As great as archive.org is, it often gets congested and as a result the download speed can drop down drastically to unbelievably slow levels.

I've been testing a few WiFi dongles recently as well as some other bits, and as a result i've reimaged and updated my MiSTer a number of times and ran the update_all script in full.

When I run the script, when it gets to MAME-GETTER and HBMAME-GETTER, even on my connection (which is fast - I also wired my MiSTer via LAN when testing), sometimes the larger ROMS (CPS 1/2 20mb+) will incur a CURL timeout due to archive.org speeds being too low. It isn't my connection btw. This CURL timeout will eventually happen even if the file IS actually downloading (albeit very, very slowly). It doesn't have to be completely idle for any timeout to kick in. But if things are taking a bit too long, and the timeout limit is hit, the download is cancelled and the script moves on.

I've noticed an issue when this happens though.

If there is a CURL timeout of any sort during transfer, it doesn't remove the affected/partially downloaded .zip file.

This means the partially downloaded zip file remains on the users system, and the file will not load.

It is possible the user may have noticed the CURL timeout if they watched the updater, or if they inspected the log afterwards for any reason. Only then would they notice there was a failure which needs actioning.

However, for the general user they might not see this and wonder what's up. If they run subsequent updates, because the file is technically on the file system (albeit incomplete), the updater assumes all is well and the problem is not resolved.

To resolve, the user has to delete it manually - the file will then try to download again when the updater is run, and hopefully archive.org is downloading at acceptable speeds to obtain it successfully.

I was wondering, can something be considered like the following:

1) If there is a CURL timeout, can the partially downloaded file be removed, so that on the next update run, it tries to download the file again?

2) Can the CURL timeout be adjusted or changed so that if the file is actually downloading, it doesn't cancel it if there is a legitimate transfer taking place? Or maybe extend the timeout further? I'd have thought any timeout should only occur if the download gets stuck, or there is no transfer for xxxx seconds, or there is a server disconnect. Not sure how best to handle this.

3) Also on 'first run' of the update_all script, for MAME-GETTER and HBMAME-GETTER it doesn't show progress of the file downloads. Not sure why this is, maybe it was kept compact/suppressed on purpose. I believe though on subsequent runs it does actually show a more verbose output with percentages/bytes transferred, etc. But not on the very first run. Kind of strange but just something I noticed.

Talking of verbose, sorry for above verbosity! Just wanted to explain in full what seems to happen. It's not a huge deal, and to be honest i'm not sure if you plan to continue using archive.org - if so it might be worth seeing if things can be tweaked a bit. I appreciate it is probably low priority.

Thanks a lot!

**Comment by theypsilon** [comment]
Hey @movisman , thanks a lot for your message. You are giving really valuable feedback here. In fact, so valuable that I just went straight to implement what you were suggesting in your points 1 and 2.

And here it is: https://github.com/atrac17/MiSTer_MAME_SCRIPTS/commit/8f76ffa015c1f8cb27be23cc8ebc94701a8dc16e

Basically I did the error handling you suggested when there was a timeout. That way, next time you run MAME GETTER, it will try to download the failed file again.

I also increased the timeout time to 5 minutes instead of 3.

In any case, the timeout parameter can be modified with the CURL_RETRY parameter on update_mame-getter.ini, like this:
`CURL_RETRY="--connect-timeout 15 --max-time 300 --retry 3 --retry-delay 5 --show-error"`

300 is the timeout in seconds, if you want to set it to one hour, just change it to 3600.

About 3. I haven't noticed what you are mentioning but I'll keep an eye on that. In any case, it doesn't seem very important.

Thanks for your message!

**Comment by movisman** [comment]
Hey @theypsilon - thanks a lot for coming back to me. I'm glad the feedback was useful.

I will do some testing and let you know if there are any issues.

So just to clarify the behaviour, if the download speed is slow due to archive.org throttling (but technically still transferring) - if the timeout parameter is still met, it will still cut the download off, correct? (so it _must_ obtain the file within 300 seconds).

But now, the next time the updater is run, with your new logic in place, it will try to redownload the file if it was cut off before it had chance to finish?

In the past, when I was left with an incomplete zip due to timeout, the only way to resolve was to clear .last_run and delete the zip file to force a resync. It would then try to get the file again. Hopefully now, that step is not necessary if the updater knows the file is incomplete and tries to grab it again on next update run.

Regarding point 3 and the verbosity/output when downloading - I have done some investigation on this and i've found out what the issue is. I will raise a fresh issue in Github with all the information, as it should be a simple fix.

Thanks a lot!

**Comment by theypsilon** [comment]
Yes, the behaviour should be the one you mention. Thanks! Checking the other issue in a sec.

**Comment by movisman** [comment]
No problem at all! I've gone into a fair bit of detail but wanted to give you all the info I discovered - hopefully it will all make sense and be a relatively easy fix (hopefully).

Once you've had a chance to take a look, i'm happy to test it out. I have a fresh/blank installation of MiSTer which I can mess about with.

Thank you!

**Comment by movisman** [comment]
You are most welcome. Thanks for creating such a brilliant script, it is absolutely invaluable for MiSTer users.
