### ISSUE TITLE
Change the way the roms directory is determined

### ISSUE THREAD

**Issue by Paradox** [atrac17/MiSTer_MAME_SCRIPTS#35]
Check the BIOS updater script for an example of how to parse a set of directories, and select the correct one. The reason for this is i use a USB drive for all of my roms, and, yes, i already set rommame and romhbmame to /media/usb0/games/(mame and hbmame) problem is, if mister decides to set my USB drive to usb1 instead, then these scripts can't find the usb0 folders, and proceed to download all the roms to /media/fat/games/... Instead of finding the directories on usb1 and only downloading new roms there. However, the BIOS updater recognizes usb1 as the correct location and works correctly.

**Comment by Paradox** [comment]
In fact, i have been looking through the code of all 3 scripts, and, technically, both the mame and hbmame scripts could be combined into one script, using the bios getter script format... But, we don't have to go that far. I'm working on adapting the relevant part to the two scripts, now.

**Comment by Paradox** [comment]
[https://github.com/atrac17/MiSTer_MAME_SCRIPTS/pull/36](url)

**Comment by Paradox** [comment]
I guess nobody else cares.

**Comment by xadox-1st** [comment]
Think this could be a solution for my scenario, too:
https://github.com/atrac17/MiSTer_MAME_SCRIPTS/issues/37
