### ISSUE TITLE
mame & hbmame rom folders and RetroNAS cifs mount folders

### ISSUE THREAD

**Issue by xadox-1st** [atrac17/MiSTer_MAME_SCRIPTS#37]
Currently I am testing a little bit with RetroNAS.
Here the game directories are mounted via cifs in the following directory:

- /media/fat/cifs/mame
- /media/fat/cifs/hbmame

But the script only checks the following local directories:

- /media/fat/games/mame
- /media/fat/games/hbmame

Can this also be checked if the cifs directories are present and then load the roms there?

**Comment by theypsilon** [comment]
This can be changed with `ROMMAME=/path/to/mame` and `ROMHBMAME=/path/to/mame` INI options. To be introduced at `update_mame-getter.ini` and `update_hbmame-getter.ini` respectively.
